define([], function() {
  return {
    "RetentionControlsHeader": "Retention controls",
    "RetentionLabelApplied": "Retention label",
    "RetentionLabelApplicationDate": "Applied",
    "RetentionLabelAppliedBy": "Applied by",
    "RecordStatus": "Record status",
    "IsDeleteAllowed": "Delete allowed",
    "BehaviorDuringRetentionPeriod": "Behavior during retention period",
    "IsMetadataUpdateAllowed": "Metadata update allowed",
    "IsContentUpdateAllowed": "Content update allowed",
    "IsLabelUpdateAllowed": "Label update allowed",
    "ToggleOnText": "Yes",
    "ToggleOffText": "No",
    "Locked": "Locked",
    "Unlocked": "Unlocked",
    "Toggling": "Toggling...",
    "ToggleLockStatus": "Toggle",
    "BehaviorRetain": "Retain",
    "BehaviorDoNotRetain": "Do not retain",
    "BehaviorRetainAsRecord": "Retain as record",
    "BehaviorRetainAsRegulatoryRecord": "Retain as regulatory record",
    "NoLabelApplied": "No retention label has been applied to this file/folder",
    "MultipleItemsSelected": "{0} items have been selected. Use the below button to clear the retention label for all selected items.",
    "ClearLabel": "Clear label",
    "LabelCleared": "The retention label has been cleared for the selected item(s).",
    "RecordStatusToggled": "This record has been {0} for editing.",
    "CloseModal": "Close",
    "CannotClearWhileUnlocked": "This record is unlocked for editing. Please lock it first before clearing the label.",
    "ClearErrorForMultipleItems": "The retention label could not be cleared for {0} out of {1} items. Possible reasons may be that the items are unlocked for editing, or that you don't have permission.",
    "ClearErrorForSingleItem": "The retention label could not be cleared for this item. A possible reasons might be that the items are unlocked for editing, or that you don't have permission.",
    "UnhandledError": "A generic error occurred while executing an HTTP-request",
    "IsMetadataUpdateAllowedTooltip": "Specifies whether updates to the item metadata (for example, the Title field) are allowed.",
    "IsDeleteAllowedTooltip": "Specifies whether item deletion is allowed.",
    "isLabelUpdateAllowedTooltip": "Specifies whether you're allowed to change the retention label on the document.",
    "IsContentUpdateAllowedTooltip": "Specifies whether updates to document content are allowed.",
    "RecordStatusTooltip": "Specifies whether the item is locked for editing.",
  }
});