define([], function () {
  return {
    BehaviorDoNotRetain: "Do not retain",
    BehaviorDuringRetentionPeriod: "Behavior during retention period",
    BehaviorRetain: "Retain",
    BehaviorRetainAsRecord: "Retain as record",
    BehaviorRetainAsRegulatoryRecord: "Retain as regulatory record",
    CannotClearWhileUnlockedTitle: "Unlocked Record",
    CannotClearWhileUnlockedMessage: "This record is unlocked for editing. Please lock it first before clearing the label.",
    CheckingItems: "Checking items",
    ClearErrorForMultipleItems: "The retention label could not be cleared for {0} out of {1} items. Possible reasons may be that the items are unlocked for editing, or that you don't have permission.",
    ClearErrorForSingleItem: "The retention label could not be cleared for this item. A possible reasons might be that the items are unlocked for editing, or that you don't have permission.",
    Clearing: "Clearing...",
    ClearingItems: "Clearing {0} items",
    ClearLabel: "Clear label",
    ClearLabelWarningTooltip: "Something went wrong while clearing the label. Click here to try again.",
    ClearLabels: "Clear all labels",
    ClearLabelsTooltip: "Click to clear all labels",
    ClearLabelConfirmationTitle: "About folders",
    ClearLabelConfirmationMessage: "The selected item is a folder. This operation does not clear the retention label from any content in the folder. It will only make sure new content created in the folder will not automatically get a retention label. Do you want to continue clearing the label from just the folder?",
    CloseModal: "Close",
    ErrorFetchingData: "An error occurred while fetching data",
    FileName: "File",
    IsContentUpdateAllowed: "Content update allowed",
    IsContentUpdateAllowedTooltip: "Specifies whether updates to document content are allowed.",
    IsDeleteAllowed: "Delete allowed",
    IsDeleteAllowedTooltip: "Specifies whether item deletion is allowed.",
    IsFirstPage: "This is the first page",
    IsLabelUpdateAllowed: "Label update allowed",
    IsLabelUpdateAllowedTooltip: "Specifies whether you're allowed to change the retention label on the document.",
    IsLastPage: "This is the last page",
    IsMetadataUpdateAllowed: "Metadata update allowed",
    IsMetadataUpdateAllowedTooltip: "Specifies whether updates to the item metadata (for example, the Title field) are allowed.",
    IsRecordLocked: "Record locked",
    ItemsDone: "items done",
    LabelCleared: "The retention label has been cleared for the selected item(s).",
    LabelClearedForLibrary: "The retention label has been cleared for all items in this library.",
    Locked: "Locked",
    LockRecords: "Lock all records",
    LockRecordsTooltip: "Click to lock all unlocked records",
    UnlockRecords: "Unlock all records",
    UnlockRecordsTooltip: "Unlock all locked records for editing",
    MultipleItemsSelected: "You have selected {0} items. Select one item at a time for more information.",
    NoLabelApplied: "No retention label has been applied to this file/folder",
    NoLabelsApplied: "No retention labels have been applied to selected files/folders",
    NoLabelsAppliedEntireLibrary: "No items with retention labels found in this library",
    No: "No",
    None: "None",
    RecordStatus: "Record status",
    RecordStatusToggled: "Record(s) have been {0} for editing.",
    RecordStatusToggledEntireLibrary: "All records in this library have been {0} for editing.",
    RecordStatusTooltip: "Specifies whether the item is locked for editing.",
    RetentionControlsHeader: "Retention controls",
    RetentionLabelApplicationDate: "Applied",
    RetentionLabelApplied: "Retention label",
    RetentionLabelAppliedBy: "Applied by",
    RetentionLabelEventDate: "Event date",
    RetentionLabelsApplied: "Retention labels",
    TakeBulkActionsSelectedItems: "Take bulk action (on selected items)",
    TakeBulkActionsSelectedItemsTooltip: "Click to take bulk actions on the selected items",
    TakeBulkActionsEntireLibrary: "Take bulk action (on entire library)",
    TakeBulkActionsEntireLibraryTooltip: "Click to take bulk actions on the entire library",
    ToggleLockStatus: "Toggle",
    ToggleOffText: "No",
    ToggleOnText: "Yes",
    Toggling: "Toggling...",
    ToggleErrorForMultipleItems: "The record could not be {0} for {1} out of {2} items.",
    ToggleErrorForSingleItem: "The record could not be {0} for this item.",
    TogglingItems: "Toggling {0} items",
    ToggleWarning: "Record status: {0}. An error occurred: {1} Click to try toggling the lock status again.",
    ToggleRecordForFolderAlertTitle: "About folders",
    ToggleRecordForFolderAlertMessage: "The selected item is a folder and cannot be unlocked.",
    ToggleRecordForNonRecordLabelAlertTitle: "Non-record label applied",
    ToggleRecordForNonRecordLabelAlertMessage: "The selected item is labelled with a non-record retention label and therefore cannot be locked.",
    ToPage: "Navigate to page {0}",    
    UnhandledError: "A generic error occurred while executing an HTTP-request",
    Unlocked: "Unlocked",
    Yes: "Yes",
  };
});
